
development:
  adapter: postgresql
  encoding: unicode
  database: happiness
  pool: 5
  username: andyleavitt
  password:
  host: localhost
  port: 55432
  data_dir: pgdata

test:
  adapter: postgresql
  encoding: unicode
  database: happiness-test
  pool: 5
  username: andyleavitt
  password:
  host: localhost
  port: 55432

production:
  adapter: postgresql
  encoding: unicode
  database: happiness-production
  pool: 5
  username: andyleavitt
  password:
  host: localhost
  port: 55432
